### ISSUE TITLE
Create Milestones and add features in each milestone for Features on Body Apps

### ISSUE THREAD

**Issue by mariobehling** [fossasia/bodyapps-web#56]
a) Feature List (add it to Feature.md)
b) Project Plan with possible milestones (Which features will be implemented at what time)
c) Technologies used

Proposed Milestones

Milestone 1, Due by June 10, 2015
Milestone 2, Due by June 26, 2015
Milestone 3, Due by July 25, 2015
Milestone 4, Due by August 21, 2015

**Comment by prasht63** [comment]
Milestone 1:
  - User Interface/User Experience : The website’s current interface is not so user friendly, and intuitive so that users can find it easier to get along the website.I plan to add a Responsive User Interface which increases the interaction between user and the website.The focus will be on Mobile .The flow of the web app should be enjoyable by user.

Milestone 2:
  - Social Media Integration : This will allow the user to login through Facebook and Twitter.Additionally users will be able to share their activity on different social media platforms.

  - Animations and Help Text : Supporting animations and help text for each body part included to help the users in measurement taking process.

  - Testing and Debugging of WebApp by a group of FOSSASIA members : This will give us feedback to improve the interaction layer. 

  - Documentation

Milestone 3: 
Exploring IntelRealSense and  its Javascript SDK to integrate it with BodyApps.

**Comment by mariobehling** [comment]
@prasht63 That is a good start. Intel Realsense is a focus. So, please do move it to milestone 1 and 2. For milestone 1 what actual features will you implement here? What about mockups of the design? "The flow should be enjoyable." What does this mean? How will the flow be? Please create a list of features for the app for version 1.
